---
title: "ETC5521 Assignment 1"
subtitle: "Australian Animal Outcomes"
team: galah
author:
  - Sen Wang
  - Muhammad Soban Qasim
date: "`r Sys.Date()`"
output: 
  html_document
---

[This assignment is for ETC5521 Assignment 1 by Team `r rmarkdown::metadata$team` comprising of `r knitr::combine_words(rmarkdown::metadata$author)`.]{style="color:#006DAE;"}


# Introduction and motivation

Animals are all around us in the sky, in the oceans, in our backyards and in our homes. What happens to animals in trouble, it could be cats, dogs, horses or livestock? Who takes care of them? The answer is Royal Society for the Prevention of cruelty to Animals.  

The RSPCA is Australia's oldest, largest and most trusted animal welfare organization, according to its description, there is a gradual increase in the number of animals every year which are received in animal shelters and adoption centres across the country. RSPCA decides to analyse the results of animals in Australia and help them.


# Data description

There are three data tables separately coming from the RSPCA, Townsville Animal Complaints and Brisbane Open Data - Animal Complaints.

1. animal_outcomes.csv

*year*: Full year
*animal_type*: Animal type (horse, wildlife, dog, cat, etc)
*outcome*: 	Animal outcome - euthanized, released, rehomed, etc
*ACT*: ACT - Australian Capital Territory
*NSW*: New South Wales
*NT*: Northern Territory
*QLD*: Queensland
*SA*: South Australia
*TAS*: Tasmania
*VIC*: Victoria
*WA*: Western Australian
*Total*: Australian Total

2. animal_complaints.csv

*Animal Type*: Animal Type
*Complaint Type*: Complaint type
*Date Received*: Date received (Month - year)
*Suburb*: Suburb/region
*Electoral Division*: Electoral Division

3. brisbane_complaints.csv

*nature*:	Nature of complaints (animal)
*animal_type*: Animal type
*category*: Category of complaint
*suburb*: Suburb where reported
*date_range*: Date range (typically 1 quarter + year)
*responsible_office*: Responsible office for the complaint
*city*: City (Brisbane)

# Questions 

Which state has highest rate for the best possible outcome for animals?

Which animal is euthanized the most throughout Australia?

What is the percentage of rehomed animals state wise?

Cats Vs Dogs who are more likely to get adopted or reclaimed?
 



# Analysis and findings

[FILL] Should include at least one plot or numerical summary for each of your questions, that helps the reader arrive at an answer. You should also write paragraphs describing the methods, summaries and findings. 

# References
